# Generated by Django 6.0.6 on 2026-06-24 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order_num']},
        ),
    ]
