# Generated by Django 6.0.6 on 2026-06-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
